[Trusted Types] Fixing scriptloading trusted type violations
eozmen410/ckeditor4 pull request #7
Opened 2023-07-25 15:23 UTC by youssef-attia

## What is the purpose of this pull request?

PR to fix violations specifically coming from scriptloading functions to help with making CKEditor [Trusted Types](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API) compatible.

2023-07-26 15:00 UTC, eozmen410 requested changes

2023-07-26 15:00 UTC, eozmen410 commented on ckeditor.js
This looks good for fixing the TT violation, but should we use the legacy conversion function for this as well?

2023-07-26 15:05 UTC, youssef-attia commented on ckeditor.js
Yep, you're right I'll copy over some of the tooling.

2023-07-26 17:41 UTC, eozmen410 commented on ckeditor.js
We can also merge the legacy conversion PR and then rebase this one, it might be easier to prevent any merge conflicts

2023-07-26 21:10 UTC, youssef-attia commented on ckeditor.js
Replaced with htmlSafeByReview

2023-07-27 16:03 UTC, eozmen410 approved these changes

2023-07-28 21:06 UTC, merged